#!/usr/bin/env python3
from pathlib import Path

from src.plox import Plox

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("file", nargs="?", type=Path)
    args = parser.parse_args()

    plox = Plox()

    if args.file:
        plox.run_file(args.file)
    else:
        plox.run_prompt()
