[project]
name = "plox"
version = "0.1.0"
description = "Python Lox Interpreter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths  = ["tests"]
