# This file is generated by generate_ast.py
from dataclasses import dataclass
from .token_type import Token


@dataclass
class Expression:
    pass


@dataclass
class Binary(Expression):
    left: Expression
    operator: Token
    right: Expression


@dataclass
class Grouping(Expression):
    expression: Expression


@dataclass
class Literal(Expression):
    value: object


@dataclass
class Unary(Expression):
    operator: Token
    right: Expression


